

    export interface ISummaryPageModel {
        effDate: Date,
        locationName: string,
        billingSystemCount: number,
        billingSystemBalance: number,
        billingSystemDays: number,
        bill49NoDxCount: number,
        bill49NoDxAmount: number,
        bill49NoDxDays: number,
        bill49OtherCount: number,
        bill49OtherAmount: number,
        bill49OtherDays: number,
        otherBillAlertsCount: number,
        otherBillAlertsAmount: number,
        otherNoBillAlertsCount: number,
        otherNoBillAlertsAmount: number,
        bill49SubtotalCount: number,
        bill49SubtotalAmount: number,
        subtotalCount: number,
        subtotalAmount: number,
        bill45Count: number,
        bill45Amount: number,
        bill45FinalBilledCount: number,
        bill45FinalBilledAmount: number,
        grandTotalCount: number,
        grandTotalAmount: number,
        inpatientCount: number,
        inpatientAmount: number,
        allOutpatientCount: number,
        allOutpatientAmount: number,
        emergencyCount: number,
        emergencyAmount: number,
        outpatientCount: number,
        outpatientAmount: number,
        surgeryCount: number,
        surgeryAmount: number,
        adgpr: number,
        sscName?: any,
        sscid?: any,
    }


    export class SummaryPageModel implements ISummaryPageModel {
        constructor(
            public effDate: Date = new Date(),
            public locationName: string = '',
            public billingSystemCount: number = 0,
            public billingSystemBalance: number = 0,
            public billingSystemDays: number = 0,
            public bill49NoDxCount: number = 0,
            public bill49NoDxAmount: number = 0,
            public bill49NoDxDays: number = 0,
            public bill49OtherCount: number = 0,
            public bill49OtherAmount: number = 0,
            public bill49OtherDays: number = 0,
            public otherBillAlertsCount: number = 0,
            public otherBillAlertsAmount: number = 0,
            public otherNoBillAlertsCount: number = 0,
            public otherNoBillAlertsAmount: number = 0,
            public bill49SubtotalCount: number = 0,
            public bill49SubtotalAmount: number = 0,
            public subtotalCount: number = 0,
            public subtotalAmount: number = 0,
            public bill45Count: number = 0,
            public bill45Amount: number = 0,
            public bill45FinalBilledCount: number = 0,
            public bill45FinalBilledAmount: number = 0,
            public grandTotalCount: number = 0,
            public grandTotalAmount: number = 0,
            public inpatientCount: number = 0,
            public inpatientAmount: number = 0,
            public allOutpatientCount: number = 0,
            public allOutpatientAmount: number = 0,
            public emergencyCount: number = 0,
            public emergencyAmount: number = 0,
            public outpatientCount: number = 0,
            public outpatientAmount: number = 0,
            public surgeryCount: number = 0,
            public surgeryAmount: number = 0,
            public adgpr: number = 0,
            public sscName?: any,
            public sscid?: any
        ) { }
    }

  function getDateToday(): Date {
    return new Date();
  }

